FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY app.js /usr/share/nginx/html/app.js
COPY ops-tools.js /usr/share/nginx/html/ops-tools.js
COPY diagnostics.js /usr/share/nginx/html/diagnostics.js
COPY style.css /usr/share/nginx/html/style.css
